# Generated by Django 5.2.14 on 2026-05-12 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(blank=True, max_length=120, verbose_name='Надзаголовок')),
                ('title', models.CharField(max_length=220, verbose_name='Заголовок')),
                ('subtitle', models.TextField(blank=True, verbose_name='Текст')),
                ('image', models.ImageField(upload_to='hero/', verbose_name='Изображение')),
                ('button_text', models.CharField(blank=True, max_length=80, verbose_name='Текст кнопки')),
                ('button_url', models.CharField(blank=True, max_length=220, verbose_name='Ссылка кнопки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Hero-слайд',
                'verbose_name_plural': 'Hero-слайды',
                'ordering': ['order', 'id'],
            },
        ),
    ]
