# Generated by Django 5.2.14 on 2026-05-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heroslide',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Фото первого экрана', 'verbose_name_plural': 'Фото первого экрана'},
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='button_text',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='button_url',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='eyebrow',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='subtitle',
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=models.ImageField(upload_to='hero/', verbose_name='Фото для слайдера'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='title',
            field=models.CharField(max_length=220, verbose_name='Название для админки'),
        ),
    ]
