# Generated by Django 5.2.14 on 2026-05-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_heroslide_options_remove_heroslide_button_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heroslide',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Слайд первого экрана', 'verbose_name_plural': 'Слайды первого экрана'},
        ),
        migrations.AddField(
            model_name='heroslide',
            name='eyebrow',
            field=models.CharField(blank=True, default='БУТИК ДЕСЕРТОВ', max_length=120, verbose_name='Надзаголовок'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='primary_button_text',
            field=models.CharField(blank=True, default='Смотреть каталог', max_length=80, verbose_name='Текст основной кнопки'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='primary_button_url',
            field=models.CharField(blank=True, default='#catalog', max_length=220, verbose_name='Ссылка основной кнопки'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='secondary_button_text',
            field=models.CharField(blank=True, default='Оставить заявку', max_length=80, verbose_name='Текст второй кнопки'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='secondary_button_url',
            field=models.CharField(blank=True, default='#order', max_length=220, verbose_name='Ссылка второй кнопки'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='subtitle',
            field=models.TextField(blank=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='title',
            field=models.CharField(max_length=220, verbose_name='Заголовок'),
        ),
    ]
