# Generated by Django 5.2.14 on 2026-07-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_cart_key_and_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='weight_unit',
            field=models.CharField(choices=[('kg', 'кг'), ('g', 'г')], default='kg', max_length=2, verbose_name='Единица'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Вес'),
        ),
    ]
