# Generated by Django 5.2.14 on 2026-07-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_weight_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='weight_unit',
            field=models.CharField(choices=[('kg', 'кг'), ('g', 'г'), ('pc', 'шт')], default='kg', max_length=2, verbose_name='Единица'),
        ),
    ]
