# Generated by Django 5.2.14 on 2026-07-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_populate_missing_slugs'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productweightoption',
            name='unique_product_weight',
        ),
        migrations.AddField(
            model_name='productweightoption',
            name='weight_unit',
            field=models.CharField(choices=[('kg', 'кг'), ('g', 'г')], default='kg', max_length=2, verbose_name='Единица'),
        ),
        migrations.AlterField(
            model_name='productweightoption',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Вес'),
        ),
        migrations.AddConstraint(
            model_name='productweightoption',
            constraint=models.UniqueConstraint(fields=('product', 'weight', 'weight_unit'), name='unique_product_weight'),
        ),
    ]
